FROM registry.access.redhat.com/ubi10-minimal

ENV HOME=/home/user
ENV BUILDAH_ISOLATION=chroot

USER 0

COPY --chown=0:0 entrypoint.sh /

RUN microdnf --disableplugin=subscription-manager install -y procps-ng openssl git tar shadow-utils bash zsh podman buildah skopeo python3-pip python3-devel aardvark-dns fuse-overlayfs util-linux vim-minimal vim-enhanced; \
    microdnf update -y ; \
    microdnf clean all ; \
    pip3 install podman-compose ; \
    chmod +x /entrypoint.sh ; \
    #
    # Setup for root-less podman
    #
    # mkdir -p ${HOME} ; \
    # chown -R 1000:1000 ${HOME} ; \
    groupadd --gid 1000 user ; \
    useradd --home-dir ${HOME} --gid 1000 --uid 1000 --groups root --shell /bin/bash user ; \
    # echo "user:x:1000:1000:devspaces user:${HOME}:/bin/bash" >> /etc/passwd ; \
    # echo "user:x:1000:" >> /etc/group ; \
    echo "user:1001:64535" >> /etc/subuid ; \
    echo "user:1001:64535" >> /etc/subgid ; \
    usermod --append --groups root user ; \
    setcap cap_setuid+ep /usr/bin/newuidmap ; \
    setcap cap_setgid+ep /usr/bin/newgidmap

ENTRYPOINT ["/usr/libexec/podman/catatonit","--","/entrypoint.sh"]
CMD [ "tail", "-f", "/dev/null" ]